/**
 * Learn from the filed-return corpus (returns-only, no ETBs):
 *  1) Parser hardening — read every real vintage; report any file the
 *     template-reader chokes on (our "ingest the client's prior return"
 *     features depend on this working for every year 2009–2026).
 *  2) Real code-usage prior — how often each CfR code is actually populated
 *     across real returns, with its canonical label. Written to
 *     src/data/code-usage.json for the mapper to prefer real-world lines.
 *
 * Usage: npx tsx scripts/learn-corpus.ts <dir-of-returns>
 */
import fs from 'node:fs';
import path from 'node:path';
import { readTemplateCodes } from '../src/template-codes';
import { readCfrValues } from '../src/template-reader';

interface Agg { count: number; label: string; sheet: string }

async function main() {
  const dir = process.argv[2];
  const files = fs.readdirSync(dir).filter((f) => /\.(xlsx|xlsm|xls)$/i.test(f));
  const usage = new Map<string, Agg>(); // key `${sheet}:${code}`
  let ok = 0;
  const failures: string[] = [];
  const perFile: Array<{ f: string; codes: number; populated: number }> = [];

  for (const f of files) {
    const buf = fs.readFileSync(path.join(dir, f));
    try {
      const codes = readTemplateCodes(buf);
      const labelOf = new Map(codes.map((c) => [`${c.sheet}:${c.code}`, c.label]));
      const vals = await readCfrValues(buf, ['B_Sheet', 'Income']);
      const populated = vals.filter((v) => v.value !== null && !v.computed && Math.abs(v.value as number) > 0.5);
      for (const v of populated) {
        const key = `${v.sheet}:${v.cfrCode}`;
        const a = usage.get(key) || { count: 0, label: labelOf.get(key) || '', sheet: v.sheet };
        a.count++;
        if (!a.label && labelOf.get(key)) a.label = labelOf.get(key)!;
        usage.set(key, a);
      }
      perFile.push({ f, codes: codes.length, populated: populated.length });
      ok++;
    } catch (e) {
      failures.push(`${f}: ${(e as Error).message}`);
    }
  }

  console.log(`\n=== PARSER HARDENING: ${ok}/${files.length} returns parsed cleanly ===`);
  for (const p of perFile) console.log(`  ${p.f}  codes=${p.codes} populated=${p.populated}`);
  if (failures.length) {
    console.log(`\n!!! ${failures.length} FAILED:`);
    failures.forEach((x) => console.log('  ' + x));
  }

  const rows = [...usage.entries()]
    .map(([key, a]) => ({ key, sheet: a.sheet, code: Number(key.split(':')[1]), count: a.count, label: a.label }))
    .sort((x, y) => y.count - x.count);
  console.log(`\n=== CODE-USAGE PRIOR: ${rows.length} distinct codes populated across ${ok} returns ===`);
  console.log('Top 25 most-used data lines:');
  for (const r of rows.slice(0, 25)) console.log(`  ${r.count}x  ${r.sheet}/${r.code}  ${r.label}`);

  // Emit a compiled-in TS module (not JSON under src/data, which is gitignored as
  // the runtime disk mount) so the prior ships and needs no runtime file IO.
  const data = rows.map(({ sheet, code, count, label }) => ({ sheet, code, count, label }));
  const ts = `/** AUTO-GENERATED by scripts/learn-corpus.ts from ${ok} filed returns. Do not edit by hand. */
export interface UsageRow { sheet: string; code: number; count: number; label: string }
export const GENERATED_FROM = ${ok};
export const CODE_USAGE: UsageRow[] = ${JSON.stringify(data, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, '..', 'src', 'code-usage-data.ts'), ts);
  console.log(`\nWrote src/code-usage-data.ts (${rows.length} codes from ${ok} returns).`);
}

main().catch((e) => (console.error(e), process.exit(1)));
