/** AUTO-GENERATED by scripts/learn-corpus.ts from 22 filed returns. Do not edit by hand. */
export interface UsageRow { sheet: string; code: number; count: number; label: string }
export const GENERATED_FROM = 22;
export const CODE_USAGE: UsageRow[] = [
  {
    "sheet": "B_Sheet",
    "code": 3801,
    "count": 22,
    "label": "Ordinary Share Capital"
  },
  {
    "sheet": "Income",
    "code": 6173,
    "count": 22,
    "label": "Audit fees"
  },
  {
    "sheet": "B_Sheet",
    "code": 3905,
    "count": 21,
    "label": "Retained Earnings"
  },
  {
    "sheet": "B_Sheet",
    "code": 3100,
    "count": 19,
    "label": "Amounts payable and accrued liabilities"
  },
  {
    "sheet": "Income",
    "code": 7501,
    "count": 19,
    "label": "Retained earnings brought forward"
  },
  {
    "sheet": "B_Sheet",
    "code": 3998,
    "count": 19,
    "label": "TOTAL SHAREHOLDER EQUITY"
  },
  {
    "sheet": "Income",
    "code": 6997,
    "count": 19,
    "label": "TOTAL OPERATING EXPENSES"
  },
  {
    "sheet": "Income",
    "code": 7050,
    "count": 19,
    "label": "NET INCOME OR LOSS ON ORDINARY ACTIVITIES BEFORE TAX"
  },
  {
    "sheet": "Income",
    "code": 7600,
    "count": 19,
    "label": "RETAINED EARNINGS CARRIED FORWARD"
  },
  {
    "sheet": "B_Sheet",
    "code": 2299,
    "count": 18,
    "label": "TOTAL ASSETS"
  },
  {
    "sheet": "B_Sheet",
    "code": 3799,
    "count": 18,
    "label": "TOTAL LIABILITIES"
  },
  {
    "sheet": "B_Sheet",
    "code": 2150,
    "count": 14,
    "label": "Cash at bank and in hand"
  },
  {
    "sheet": "B_Sheet",
    "code": 3300,
    "count": 13,
    "label": "Due to shareholder(s) and / or director(s) and / or related parties"
  },
  {
    "sheet": "Income",
    "code": 5499,
    "count": 13,
    "label": "TOTAL REVENUE"
  },
  {
    "sheet": "Income",
    "code": 6170,
    "count": 13,
    "label": "Professional fees"
  },
  {
    "sheet": "Income",
    "code": 6203,
    "count": 10,
    "label": "Company registration fee"
  },
  {
    "sheet": "B_Sheet",
    "code": 3101,
    "count": 10,
    "label": "Trade creditors"
  },
  {
    "sheet": "Income",
    "code": 5000,
    "count": 9,
    "label": "Sale of goods and rendering of services"
  },
  {
    "sheet": "Income",
    "code": 6345,
    "count": 9,
    "label": "Bank Charges"
  },
  {
    "sheet": "Income",
    "code": 6608,
    "count": 9,
    "label": "General and administrative expenses"
  },
  {
    "sheet": "Income",
    "code": 6172,
    "count": 8,
    "label": "Accountancy fees"
  },
  {
    "sheet": "Income",
    "code": 6313,
    "count": 8,
    "label": "Telephone and telecommunications"
  },
  {
    "sheet": "Income",
    "code": 6020,
    "count": 8,
    "label": "Wages, Salaries and Employee benefits"
  },
  {
    "sheet": "B_Sheet",
    "code": 2052,
    "count": 7,
    "label": "Trade debtors"
  },
  {
    "sheet": "Income",
    "code": 6600,
    "count": 6,
    "label": "Other expenses"
  },
  {
    "sheet": "B_Sheet",
    "code": 2205,
    "count": 6,
    "label": "Prepaid expenses, advances, tender deposits, etc.."
  },
  {
    "sheet": "Income",
    "code": 5998,
    "count": 6,
    "label": "COST OF SALES"
  },
  {
    "sheet": "Income",
    "code": 6220,
    "count": 6,
    "label": "Rental"
  },
  {
    "sheet": "B_Sheet",
    "code": 1389,
    "count": 5,
    "label": "Computers and Electronic Equipment"
  },
  {
    "sheet": "B_Sheet",
    "code": 1390,
    "count": 5,
    "label": "Accumulated depreciation of computers and electronic equipment"
  },
  {
    "sheet": "B_Sheet",
    "code": 1393,
    "count": 5,
    "label": "Furniture, Fixtures, Fittings and Soft Furnishings"
  },
  {
    "sheet": "Income",
    "code": 6448,
    "count": 5,
    "label": "Depreciation of computers and electronic equipment"
  },
  {
    "sheet": "B_Sheet",
    "code": 3203,
    "count": 5,
    "label": "VAT payable"
  },
  {
    "sheet": "B_Sheet",
    "code": 3400,
    "count": 5,
    "label": "Other current liabilities"
  },
  {
    "sheet": "Income",
    "code": 5600,
    "count": 5,
    "label": "Direct Costs"
  },
  {
    "sheet": "Income",
    "code": 6140,
    "count": 5,
    "label": "Office Expenses"
  },
  {
    "sheet": "Income",
    "code": 6295,
    "count": 5,
    "label": "Computer-related expenses"
  },
  {
    "sheet": "B_Sheet",
    "code": 2200,
    "count": 5,
    "label": "Other current assets"
  },
  {
    "sheet": "B_Sheet",
    "code": 3202,
    "count": 5,
    "label": "CIR - FSS and NI payable"
  },
  {
    "sheet": "B_Sheet",
    "code": 1394,
    "count": 4,
    "label": "Accumulated depreciation of furniture, fixtures, fittings and soft furnishings"
  },
  {
    "sheet": "Income",
    "code": 6000,
    "count": 4,
    "label": "Advertising and promotion"
  },
  {
    "sheet": "Income",
    "code": 6025,
    "count": 4,
    "label": "Directors' salaries and remuneration"
  },
  {
    "sheet": "Income",
    "code": 6171,
    "count": 4,
    "label": "Legal fees"
  },
  {
    "sheet": "Income",
    "code": 6450,
    "count": 4,
    "label": "Depreciation of furniture, fixtures, fittings and soft furnishings"
  },
  {
    "sheet": "B_Sheet",
    "code": 2100,
    "count": 4,
    "label": "Due from shareholder(s) and / or director(s) and related parties - current portion"
  },
  {
    "sheet": "B_Sheet",
    "code": 3201,
    "count": 4,
    "label": "CIR - Corporation Tax payable"
  },
  {
    "sheet": "Income",
    "code": 6028,
    "count": 4,
    "label": "Employer's share of Social Security Contributions"
  },
  {
    "sheet": "Income",
    "code": 6120,
    "count": 4,
    "label": "Insurance"
  },
  {
    "sheet": "Income",
    "code": 6250,
    "count": 4,
    "label": "Repairs and maintenance"
  },
  {
    "sheet": "Income",
    "code": 6311,
    "count": 4,
    "label": "Water and Electricity"
  },
  {
    "sheet": "B_Sheet",
    "code": 2050,
    "count": 3,
    "label": "Accounts receivable"
  },
  {
    "sheet": "B_Sheet",
    "code": 2203,
    "count": 3,
    "label": "Income Tax refundable"
  },
  {
    "sheet": "Income",
    "code": 6141,
    "count": 3,
    "label": "Office stationery and supplies"
  },
  {
    "sheet": "Income",
    "code": 6201,
    "count": 3,
    "label": "Membership and subscription fees"
  },
  {
    "sheet": "Income",
    "code": 7060,
    "count": 3,
    "label": "Current tax provision"
  },
  {
    "sheet": "Income",
    "code": 6381,
    "count": 3,
    "label": "Unrealised Loss or Gain on Exchange"
  },
  {
    "sheet": "Income",
    "code": 5300,
    "count": 3,
    "label": "Other Income"
  },
  {
    "sheet": "Income",
    "code": 6100,
    "count": 3,
    "label": "Travel Expenses"
  },
  {
    "sheet": "Income",
    "code": 6340,
    "count": 3,
    "label": "Interest and bank charges"
  },
  {
    "sheet": "B_Sheet",
    "code": 1372,
    "count": 2,
    "label": "Air-conditioners"
  },
  {
    "sheet": "B_Sheet",
    "code": 1373,
    "count": 2,
    "label": "Accumulated depreciation of Air-conditioners"
  },
  {
    "sheet": "Income",
    "code": 6003,
    "count": 2,
    "label": "Meals and entertainment"
  },
  {
    "sheet": "Income",
    "code": 6346,
    "count": 2,
    "label": "Realised Loss or Gain on Exchange"
  },
  {
    "sheet": "B_Sheet",
    "code": 1764,
    "count": 2,
    "label": "Shares in foreign Companies"
  },
  {
    "sheet": "B_Sheet",
    "code": 1734,
    "count": 2,
    "label": "Shares in foreign related Companies"
  },
  {
    "sheet": "B_Sheet",
    "code": 3550,
    "count": 2,
    "label": "Long-term amounts due to shareholder(s) /director(s) and / or related parties"
  },
  {
    "sheet": "B_Sheet",
    "code": 1731,
    "count": 2,
    "label": "Shares in local related Companies"
  },
  {
    "sheet": "B_Sheet",
    "code": 2204,
    "count": 2,
    "label": "VAT refundable"
  },
  {
    "sheet": "B_Sheet",
    "code": 3000,
    "count": 2,
    "label": "Bank overdraft"
  },
  {
    "sheet": "Income",
    "code": 5308,
    "count": 2,
    "label": "Subsidies and grants"
  },
  {
    "sheet": "Income",
    "code": 5550,
    "count": 2,
    "label": "Purchases"
  },
  {
    "sheet": "Income",
    "code": 6001,
    "count": 2,
    "label": "Advertising"
  },
  {
    "sheet": "Income",
    "code": 6312,
    "count": 2,
    "label": "Fuel costs"
  },
  {
    "sheet": "Income",
    "code": 6611,
    "count": 2,
    "label": "Motor Vehicles Running Costs"
  },
  {
    "sheet": "B_Sheet",
    "code": 1350,
    "count": 2,
    "label": "Plant and machinery"
  },
  {
    "sheet": "B_Sheet",
    "code": 1351,
    "count": 2,
    "label": "Accumulated depreciation of plant and machinery"
  },
  {
    "sheet": "B_Sheet",
    "code": 1763,
    "count": 2,
    "label": "Shares in local Companies"
  },
  {
    "sheet": "Income",
    "code": 6037,
    "count": 2,
    "label": "Commissions"
  },
  {
    "sheet": "Income",
    "code": 6449,
    "count": 2,
    "label": "Depreciation of computer software"
  },
  {
    "sheet": "Income",
    "code": 7080,
    "count": 2,
    "label": "Deferred tax provision"
  },
  {
    "sheet": "B_Sheet",
    "code": 3301,
    "count": 1,
    "label": "Short-term loans and / or advances due to individual shareholder(s)"
  },
  {
    "sheet": "B_Sheet",
    "code": 1700,
    "count": 1,
    "label": "Due from shareholder(s) and / or director(s)"
  },
  {
    "sheet": "B_Sheet",
    "code": 3104,
    "count": 1,
    "label": "Wages and salaries payable"
  },
  {
    "sheet": "B_Sheet",
    "code": 3403,
    "count": 1,
    "label": "Deferred income tax"
  },
  {
    "sheet": "Income",
    "code": 6291,
    "count": 1,
    "label": "Loose tools"
  },
  {
    "sheet": "B_Sheet",
    "code": 2151,
    "count": 1,
    "label": "Deposits in Maltese banks and institutions - Maltese currency"
  },
  {
    "sheet": "Income",
    "code": 6032,
    "count": 1,
    "label": "Staff Training & Education"
  },
  {
    "sheet": "B_Sheet",
    "code": 3552,
    "count": 1,
    "label": "Long-term loans due to corporate shareholder(s)"
  },
  {
    "sheet": "B_Sheet",
    "code": 2105,
    "count": 1,
    "label": "Loans, advances and demand notes from related parties - current portion"
  },
  {
    "sheet": "B_Sheet",
    "code": 1740,
    "count": 1,
    "label": "Loans to third parties"
  },
  {
    "sheet": "B_Sheet",
    "code": 2101,
    "count": 1,
    "label": "Due from individual shareholder(s) - current portion"
  },
  {
    "sheet": "B_Sheet",
    "code": 3390,
    "count": 1,
    "label": "Short-term loans to third parties"
  },
  {
    "sheet": "B_Sheet",
    "code": 3500,
    "count": 1,
    "label": "Long term debt"
  },
  {
    "sheet": "Income",
    "code": 5284,
    "count": 1,
    "label": "Realised gains or losses on sale of investments"
  },
  {
    "sheet": "B_Sheet",
    "code": 1735,
    "count": 1,
    "label": "Loans and / or advances to foreign related companies"
  },
  {
    "sheet": "B_Sheet",
    "code": 3900,
    "count": 1,
    "label": "Reserves"
  },
  {
    "sheet": "Income",
    "code": 5112,
    "count": 1,
    "label": "Dividends from foreign sources"
  },
  {
    "sheet": "B_Sheet",
    "code": 3022,
    "count": 1,
    "label": "Local bank loan(s) - [Current portion]"
  },
  {
    "sheet": "B_Sheet",
    "code": 3904,
    "count": 1,
    "label": "Incentives and Benefits Reserve [BPA]"
  },
  {
    "sheet": "Income",
    "code": 5554,
    "count": 1,
    "label": "Freight, Insurance and Duty on Imported Goods"
  },
  {
    "sheet": "Income",
    "code": 5603,
    "count": 1,
    "label": "Hire of Machinery & Equipment"
  },
  {
    "sheet": "Income",
    "code": 6224,
    "count": 1,
    "label": "Equipment rental"
  },
  {
    "sheet": "Income",
    "code": 6605,
    "count": 1,
    "label": "Royalty expenses - resident"
  },
  {
    "sheet": "Income",
    "code": 5190,
    "count": 1,
    "label": "Commission Income"
  },
  {
    "sheet": "Income",
    "code": 6200,
    "count": 1,
    "label": "Licences, permits and membership"
  },
  {
    "sheet": "Income",
    "code": 6440,
    "count": 1,
    "label": "Depreciation of Air-conditioners"
  },
  {
    "sheet": "Income",
    "code": 7502,
    "count": 1,
    "label": "Dividends proposed during the year"
  },
  {
    "sheet": "Income",
    "code": 6430,
    "count": 1,
    "label": "Depreciation of Tangible Assets"
  },
  {
    "sheet": "B_Sheet",
    "code": 1610,
    "count": 1,
    "label": "Leasehold improvements"
  },
  {
    "sheet": "B_Sheet",
    "code": 1006,
    "count": 1,
    "label": "Royalties, trademarks, patents, rights, etc."
  },
  {
    "sheet": "B_Sheet",
    "code": 1007,
    "count": 1,
    "label": "Accumulated amortisation of royalties, trademarks, patents"
  },
  {
    "sheet": "B_Sheet",
    "code": 1802,
    "count": 1,
    "label": "Deferred items and / or charges"
  },
  {
    "sheet": "B_Sheet",
    "code": 3304,
    "count": 1,
    "label": "Short-term loans and / or advances due to related parties"
  },
  {
    "sheet": "B_Sheet",
    "code": 3805,
    "count": 1,
    "label": "Share Premium Account"
  },
  {
    "sheet": "Income",
    "code": 6403,
    "count": 1,
    "label": "Amortisation of royalties, trademarks, patents"
  },
  {
    "sheet": "B_Sheet",
    "code": 1612,
    "count": 1,
    "label": "Capital assets under construction"
  },
  {
    "sheet": "B_Sheet",
    "code": 3555,
    "count": 1,
    "label": "Long-term loans due to foreign related parties"
  },
  {
    "sheet": "B_Sheet",
    "code": 1391,
    "count": 1,
    "label": "Computer software"
  },
  {
    "sheet": "B_Sheet",
    "code": 1392,
    "count": 1,
    "label": "Accumulated depreciation of computer software"
  },
  {
    "sheet": "B_Sheet",
    "code": 2155,
    "count": 1,
    "label": "Cash"
  },
  {
    "sheet": "B_Sheet",
    "code": 3405,
    "count": 1,
    "label": "General Provisions"
  },
  {
    "sheet": "B_Sheet",
    "code": 3906,
    "count": 1,
    "label": "Non-distributable reserves"
  },
  {
    "sheet": "Income",
    "code": 6034,
    "count": 1,
    "label": "Staff Welfare"
  },
  {
    "sheet": "Income",
    "code": 6099,
    "count": 1,
    "label": "Sub-contracting and Out-sourcing"
  }
];
